before_script:
  - "bundle exec rake test_app"
script: "DISPLAY=:99.0 bundle exec rspec spec"
notifications:
  email:
    - ecl1pse.armageddon@gmail.com
branches:
  only:
    - master
rvm:
  - 1.9.3
  - 2.0.0
